package business.table;

public class HelloWorldTable {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column AUTH.AUTHCD
     *
     * @mbggenerated Fri Nov 20 16:35:07 CST 2015
     */
    private String authcd;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column AUTH.AUTHDESC
     *
     * @mbggenerated Fri Nov 20 16:35:07 CST 2015
     */
    private String authdesc;



    private String authtypcd;
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column AUTH.AUTHSTATCD
     *
     * @mbggenerated Fri Nov 20 16:35:07 CST 2015
     */
    private String authstatcd;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column AUTH.HBNKACTIVATEDYN
     *
     * @mbggenerated Fri Nov 20 16:35:07 CST 2015
     */
    private String hbnkactivatedyn;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column AUTH.BBNKACTIVATEDYN
     *
     * @mbggenerated Fri Nov 20 16:35:07 CST 2015
     */
    private String bbnkactivatedyn;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column AUTH.DATELASTMAINT
     *
     * @mbggenerated Fri Nov 20 16:35:07 CST 2015
     */
    private Long datelastmaint;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column AUTH.AUTHNAME
     *
     * @mbggenerated Fri Nov 20 16:35:07 CST 2015
     */
    private String authname;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column AUTH.AUTHCD
     *
     * @return the value of AUTH.AUTHCD
     *
     * @mbggenerated Fri Nov 20 16:35:07 CST 2015
     */
    public String getAuthcd() {
        return authcd;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column AUTH.AUTHCD
     *
     * @param authcd the value for AUTH.AUTHCD
     *
     * @mbggenerated Fri Nov 20 16:35:07 CST 2015
     */
    public void setAuthcd(String authcd) {
        this.authcd = authcd;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column AUTH.AUTHDESC
     *
     * @return the value of AUTH.AUTHDESC
     *
     * @mbggenerated Fri Nov 20 16:35:07 CST 2015
     */
    public String getAuthdesc() {
        return authdesc;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column AUTH.AUTHDESC
     *
     * @param authdesc the value for AUTH.AUTHDESC
     *
     * @mbggenerated Fri Nov 20 16:35:07 CST 2015
     */
    public void setAuthdesc(String authdesc) {
        this.authdesc = authdesc;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column AUTH.AUTHSTATCD
     *
     * @return the value of AUTH.AUTHSTATCD
     *
     * @mbggenerated Fri Nov 20 16:35:07 CST 2015
     */
    public String getAuthstatcd() {
        return authstatcd;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column AUTH.AUTHSTATCD
     *
     * @param authstatcd the value for AUTH.AUTHSTATCD
     *
     * @mbggenerated Fri Nov 20 16:35:07 CST 2015
     */
    public void setAuthstatcd(String authstatcd) {
        this.authstatcd = authstatcd;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column AUTH.HBNKACTIVATEDYN
     *
     * @return the value of AUTH.HBNKACTIVATEDYN
     *
     * @mbggenerated Fri Nov 20 16:35:07 CST 2015
     */
    public String getHbnkactivatedyn() {
        return hbnkactivatedyn;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column AUTH.HBNKACTIVATEDYN
     *
     * @param hbnkactivatedyn the value for AUTH.HBNKACTIVATEDYN
     *
     * @mbggenerated Fri Nov 20 16:35:07 CST 2015
     */
    public void setHbnkactivatedyn(String hbnkactivatedyn) {
        this.hbnkactivatedyn = hbnkactivatedyn;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column AUTH.BBNKACTIVATEDYN
     *
     * @return the value of AUTH.BBNKACTIVATEDYN
     *
     * @mbggenerated Fri Nov 20 16:35:07 CST 2015
     */
    public String getBbnkactivatedyn() {
        return bbnkactivatedyn;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column AUTH.BBNKACTIVATEDYN
     *
     * @param bbnkactivatedyn the value for AUTH.BBNKACTIVATEDYN
     *
     * @mbggenerated Fri Nov 20 16:35:07 CST 2015
     */
    public void setBbnkactivatedyn(String bbnkactivatedyn) {
        this.bbnkactivatedyn = bbnkactivatedyn;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column AUTH.DATELASTMAINT
     *
     * @return the value of AUTH.DATELASTMAINT
     *
     * @mbggenerated Fri Nov 20 16:35:07 CST 2015
     */
    public Long getDatelastmaint() {
        return datelastmaint;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column AUTH.DATELASTMAINT
     *
     * @param datelastmaint the value for AUTH.DATELASTMAINT
     *
     * @mbggenerated Fri Nov 20 16:35:07 CST 2015
     */
    public void setDatelastmaint(Long datelastmaint) {
        this.datelastmaint = datelastmaint;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column AUTH.AUTHNAME
     *
     * @return the value of AUTH.AUTHNAME
     *
     * @mbggenerated Fri Nov 20 16:35:07 CST 2015
     */
    public String getAuthname() {
        return authname;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column AUTH.AUTHNAME
     *
     * @param authname the value for AUTH.AUTHNAME
     *
     * @mbggenerated Fri Nov 20 16:35:07 CST 2015
     */
    public void setAuthname(String authname) {
        this.authname = authname;
    }

    public String getAuthtypcd() {
        return authtypcd;
    }

    public void setAuthtypcd(String authtypcd) {
        this.authtypcd = authtypcd;
    }
}
